# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TestDamo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
   pod 'Flurry-iOS-SDK/FlurrySDK'
   pod 'CocoaLumberjack'
   pod 'MLeaksFinder'
   pod 'FBRetainCycleDetector'
  # Pods for TestDamo

end
